version: "3.8"

services:
  backend:
    build: ./backend
    container_name: healthgo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./frontend
    container_name: healthgo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
